name: egp
channels:
- defaults
- conda-forge
dependencies:
- scipy
- numpy
- scikit-learn
- matplotlib
- pandas
- numba
- h5py
- xarray
- pytables
- dask
- cartopy
# GP Libraries
- pytorch::pytorch
- pytorch::torchvision
- pytorch::cpuonly
- pip
- pip:
    - pyro-ppl
    - emukit
    - GPy
    - tensorflow
    - tensorflow_probability
    - git+https://github.com/GPflow/GPflow.git@develop#egg=gpflow